spring:
  application:
    name: discovery

server:
  port: ${SERVER_PORT:3000}


eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:3000}/eureka/

